name: malltiverse_timbu
description: "A jejelove shopping app built with timbu api and flutter for HNG 11 Internship."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  flutter_lorem: ^2.0.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.0
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - font/
 
  fonts:
    - family: JtCart
      fonts:
        - asset: font/JtCart.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  