import 'package:flutter/widgets.dart';
/// Flutter icons JtCart
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JtCart
///      fonts:
///       - asset: fonts/JtCart.ttf
///
/// 
///

class JtCart {
  JtCart._();

  static const _kFontFam = 'JtCart';
  static const String? _kFontPkg = null;

  static const IconData shopcart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
